### PR TITLE
Gh168

### PR DESCRIPTION
**Pull request by jacobbuettner**
For a donor to create an account without sponsoring a child, they first click on the login button, then they click on the create account link.  This will open up a overlay where they can enter their information for their account.  The background color is just gray because I couldn't think of a good color for the background, I think we can leave that up to the designer.  If the account creation is successful the user will be alerted and the overlay will be closed and they will be logged in.  If there is an error an error message will popup and let them know.

### CODE REVIEW

**Comment by joshuarichard** [comment]
found lint :(

**Comment by jacobbuettner** [comment]
#168

**Comment by joshuarichard** [comment]
Wanna fix that lint?

**Comment by joshuarichard** [comment]
found lint :(

**Comment by jacobbuettner** [comment]
That's weird, my checkstyle passed when I ran it...Not sure what is wants me to fix then

**Comment by joshuarichard** [comment]
found lint :(

**Comment by joshuarichard** [comment]
retest this please

**Comment by joshuarichard** [comment]
yeah it's clean, idk what's with jenkins... it said line 513 in account.js had double quotes instead of single but it definitely uses single quotes.... whatever jenkins

**Comment by joshuarichard** [comment]
found lint :(

**Comment by joshuarichard** [comment]
found lint :(

**Pull request merged**
