### PR TITLE
email admin when donors request removal of their child sponsorships

### LINKED ISSUE #216: offer donors the option to remove sponsorship
code was already in place and working but brian gave the red light on programmatically removing sponsorships and deleting accounts.

reuse that code on the admin page.

for now, the system needs to hit an api route which emails the admin that a given donor wants to either remove their account or delete their sponsorship. add a "remove" button on the account page, and also add an option to delete their account on the "edit donor information" tab of the account page.

### PR DESCRIPTION
**Pull request by joshuarichard**
fixes #216 

to test:
1) add your email and password to the config file
2) `node app.js`
3) login to your account
4) click the `eliminar` button on the list of children you're sponsoring
5) check your email for an from yourself on your request for child unsponsorship

### CODE REVIEW

**Comment by joshuarichard** [comment]
found lint :(

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by jacobbuettner** [comment]
@joshuarichard Worked for me, one thing we may want to account for.  The user can keep clicking the eliminar button even after the first request is submitted.  We should probably disable the elminar button after the first successful request so the admins don't get spammed.

**Comment by jacobbuettner** [comment]
image

**Pull request merged**
