### PR TITLE
Gh224

### PR DESCRIPTION
**Pull request by compassface**
nav buttons and icon in headers

### CODE REVIEW

**Comment by joshuarichard** [comment]
found lint :(

**Comment by jacobbuettner** [comment]
Haven't had a chance to fully test this yet but one change that I see that should be made is how your hiding the nav bars.  It would be better to set the element to display = none when creating it and then using the .hide or .show to interact with it.  So you would put slide.style.display = 'none'; on line 124 when creating the slide, and then you can take out $('.nav-buttons').hide(); on line 177.

**Comment by joshuarichard** [comment]
Also, fix lint and rebase with Master you're roughly 20 commits behind

**Comment by jacobbuettner** [comment]
I'm not a big fan of pushing the footer down by setting a really big margin-bottom because it leaves a lot of empty white space between the content and the footer.  This might be a good solution http://codepen.io/chriscoyier/pen/uwJjr?editors=1100

**Comment by joshuarichard** [comment]
agreed ^

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by compassface** [comment]
dont merge yet

**Comment by joshuarichard** [comment]
lolllllll

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by jacobbuettner** [comment]
stuff is being cut off on the children page 
image

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by jacobbuettner** [comment]
Alright, I spent a good amount of time fixing this one up so I'm pretty sure its good to go now.  This pr addresses #224 and #237

**Pull request merged**
