### PR TITLE
Gh215

### PR DESCRIPTION
**Pull request by jacobbuettner**
Takes care of #215 Adds a change password button to the account information tab on account.html that users can use to change their password.  They will have to enter their current(or old, however you want to think of it) which will be authenticated with donor/auth, and their new password twice.

The submit info changes button should not exist while the submit new password but exists.  We don't want the user submitting both a new password and updating their info.

### CODE REVIEW

**Comment by joshuarichard** [comment]
found lint :(

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by joshuarichard** [comment]
1) what are we doing about the delete account button? right now it looks kind of sloppy the two on top of each other in different sizes and with no whitespace in between.
screen shot 2016-03-21 at 12 53 36 am
screen shot 2016-03-21 at 12 58 11 am

2) I see that the code doesn't add the personal information into the api call that changes the password, which is great - but can you just disable the forms like we did on the autofill form?

3) I was getting a `confirmPassword not defined` error, but I fixed it for you

4) i change the ids to some more predictable names
old password - `#form-old-password`
new password - `#form-password`
confirm password `#form-confirm-password`

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by jacobbuettner** [comment]
@joshuarichard I think we should take out the delete button and make it a tab like Tuck was saying.  I've created #246 for this issue.  As far as disabling the form, I think its a bit overkill since they cannot submit changes to their info while changing their password anyways.

**Comment by joshuarichard** [comment]
I agree on the delete account button, I'll add in the disabled form if you're feeling like you're done with this issue

**Comment by joshuarichard** [comment]
success! no lint!

**Pull request merged**
