### PR TITLE
add email and password option to checkout page

### LINKED ISSUE #134: donor's should be prompted to enter their email and password on child sponsorship
add email, and two password (password and password confirmation) text boxes to checkout.js

### PR DESCRIPTION
**Pull request by joshuarichard**
fixes #134 

adds email and password option to checkout page
also makes use of new /api/v1/donor/auth to get a donor's id for adding to child docs

### CODE REVIEW

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by jacobbuettner** [comment]
Tried to sponsor child 56b537dc2847b05257564d4b but based on what I got back from Postman it looks like the child has not been updated to reflect my sponsorship because it does not have a status field.

**Comment by joshuarichard** [comment]
you don't get the status field from the api, there's a document trim that happens because not all child information needs to be available via api. checking using rock mongo it looks like it did work though

screen shot 2016-02-08 at 5 52 02 pm

this is the donor, yeah?
screen shot 2016-02-08 at 5 52 23 pm

`data/mongo.js`:
screen shot 2016-02-08 at 5 50 03 pm

**Comment by joshuarichard** [comment]
success! no lint!

**Pull request merged**
