### PR TITLE
Gh284

### PR DESCRIPTION
**Pull request by jacobbuettner**
#284 Adds the checkout total to the donor cart on the checkout page and to step 3 (donor info confirmation) of the checkout process.  Splits cart in session storage and multiples number of children by 200 quetzals.  Q is the symbol for quetzals according to wikipedia.

### CODE REVIEW

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by jacobbuettner** [comment]
Found bug: If you have children in your DB cart, but session storage is clear, the total will only count the children in session storage.  So if a donor has two kids in their cart, then logs out which clears sessionStorage, then logs back in and chooses another child, the total will be 200 Q but 3 children will show up because of the one from sessionStorage and the 2 from the cart

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by joshuarichard** [comment]
found lint :(

**Comment by joshuarichard** [comment]
success! no lint!

**Pull request merged**
