### PR TITLE
Gh252

### PR DESCRIPTION
**Pull request by jacobbuettner**
Pulled out some stuff from the views #252 and added form validation on the account #276.  Create account, create account overlay, and form validation are now in there own files.  The whole create account overlay can now be used by simply including <div class="create-account-overlay" align="center"> in the html and $('.create-account').click(toggleCreateAccount); in the js.

### CODE REVIEW

**Comment by joshuarichard** [comment]
found lint :(

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by jacobbuettner** [comment]
Resolved conflicts, don't know why it says 21 changed files now.  Don't merge yet, everything seems to be working except for when you create a new account you are not automatically logged in after the account is created.

**Comment by jacobbuettner** [comment]
Abandoning this for now since it's not a high priority and it looks like it'll take a lot of re-working to get this to work properly and securely.

**Pull request closed without merging**
