### PR TITLE
Gh91

### LINKED ISSUE #154: put the login portal freakin' everywhere
every header everywhere put it there

talk with jake about what html/css/js needs to be on the page for login to be in the top left header

### PR DESCRIPTION
**Pull request by jacobbuettner**
Most of this was done in #113 and #114.  This adds the login overlay to all pages (index, children.html, and checkout.html).  I am going to close #154 since this takes care of that issue.

### CODE REVIEW

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by jacobbuettner** [comment]
@compassface to test this, make sure the portal is on the three pages mentioned and works correctly.

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by joshuarichard** [comment]
found lint :(

**Comment by joshuarichard** [comment]
found lint :(

**Pull request merged**
