### PR TITLE
hesitantly adding footer fixes

### PR DESCRIPTION
**Pull request by compassface**

### CODE REVIEW

**Comment by compassface** [comment]
#306

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by compassface** [comment]
see if it looks okay in your pitiful resolution screens

**Comment by joshuarichard** [comment]
sorry dude
screen shot 2016-04-24 at 3 33 58 pm
screen shot 2016-04-24 at 3 34 23 pm
screen shot 2016-04-24 at 3 34 44 pm

**Pull request closed without merging**
