### PR TITLE
two token expiring bugs

### LINKED ISSUE #208: Bugs when account expires
Everything craps out when you've expired. We need to delete all session storage and delete the cart when the token is expired and have them sign in again.

Idea: When on the checkout page and token is expired after being alerted that it's expired, delete session storage token, id , and cart, then reroute to home page to fix everything. I'm thinking clean reset when they are logged out.

### PR DESCRIPTION
**Pull request by joshuarichard**
fixes #208 

nukes everything (cart, id, token, and assignedDonorID (just in case?)) when donor's token is expired on both the account page and the checkout page. redirects to children.html.

to test - change the "expiresIn" field on line 271 in app.js from '1h' to just the number 1. this will change the amount of time the tokens last from one hour to one second. now, you'll be able to easily test. login then go to the checkout page or account page. it should tell you you've expired and boot you back to the children page, nuking your cart and everything else it can get it's grimy little hands on.

### CODE REVIEW

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by joshuarichard** [comment]
success! no lint!

**Comment by jacobbuettner** [comment]
This works for me.  I think we should consider adding more functionality to this in the future.  

While the whole point of this check is to free up the kids in the cart if the user is hogging them, I think it would be annoying for a user to have to reselect all the kids they want to sponsor again if their cart expires on them.  Especially since they will have to remember the names of all the kids in order to find them all again.

We may also want to not always forward the user to the children page after their account expires.  We could add a pop-up that will let them log in again, or even just hit "continue session", which will let them continue working without losing their progress (essentially renew their token).

**Comment by joshuarichard** [comment]
yeah I agree we could work with this a little bit, but that would be much later down the road once the project is actually completed.

for now it's good that it nukes everything because it gets rid of a lot of bugs

**Pull request merged**
